// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJVF81WHobRz2h6q_3rjEYhTqJ-R61cs',
    appId: '1:896394351169:web:d7e5f0d4db9465f5dc6cc0',
    messagingSenderId: '896394351169',
    projectId: 'quran-f329a',
    authDomain: 'quran-f329a.firebaseapp.com',
    storageBucket: 'quran-f329a.appspot.com',
    measurementId: 'G-5H75K0YRTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHxJjMYtVI7SM9oAz1iIEyFh3l5uNbb_Q',
    appId: '1:896394351169:android:0d26ea6b448b8fb3dc6cc0',
    messagingSenderId: '896394351169',
    projectId: 'quran-f329a',
    storageBucket: 'quran-f329a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdknxhycgKISM-__juXFGVhargm6okiw',
    appId: '1:896394351169:ios:53feab207318569bdc6cc0',
    messagingSenderId: '896394351169',
    projectId: 'quran-f329a',
    storageBucket: 'quran-f329a.appspot.com',
    iosClientId: '896394351169-6e6okir6ft75ltmele1i6a6f1d6gfgdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdknxhycgKISM-__juXFGVhargm6okiw',
    appId: '1:896394351169:ios:0b753b8b9cf5294edc6cc0',
    messagingSenderId: '896394351169',
    projectId: 'quran-f329a',
    storageBucket: 'quran-f329a.appspot.com',
    iosClientId: '896394351169-tfve0hum26llbm67lahpdud93iqvhnme.apps.googleusercontent.com',
    iosBundleId: 'com.example.quran.RunnerTests',
  );
}
